# Central configuration for the v2 Held-Out protocol.
#
# Usage in every v2 notebook: the notebooks resolve the project root
# themselves (KUSA_ROOT, then a list of candidate paths) and then do
#     from config import *
#     from models import *
# so no Drive path is hardcoded anywhere.
import os

# ---------------------------------------------------------------- Paths
# Portable: V2 is the directory that contains this config.py, so every data path
# below resolves relative to the checkout, in Colab or locally. Override with the
# KUSA_ROOT environment variable if config.py lives outside the project tree.
V2   = os.environ.get("KUSA_ROOT", os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.dirname(V2)

# All data resides within the project root - the folder is self-contained.
DATA = V2 + "/datasets"

ORIGINAL     = DATA + "/KurdiSent.csv"                 # Raw corpus, read-only
PREPROCESSED = DATA + "/KurdiSent_preprocessed.csv"    # Generated by preprocess_kurdisent_v2

SPLITS      = V2 + "/splits"
DEV_POOL    = SPLITS + "/dev_pool.csv"
DEV_FOLDS   = SPLITS + "/dev_folds.csv"
TEST_LOCKED = SPLITS + "/test_LOCKED.csv"
MANIFEST    = SPLITS + "/split_manifest.json"
DISTRIB     = SPLITS + "/split_distribution.csv"

FINAL_MODELS = V2 + "/final_models"
TEST_EVAL    = V2 + "/test_eval"
ANALYSIS     = V2 + "/analysis"
ANNOTATION = V2 + "/annotation"

# ---------------------------------------------------------------- Seeds
SPLIT_SEED = 2026        # test hold-out AND fold assignment (build_split_v2)
HPO_SEED   = 2026        # Optuna TPE sampler seed only

# The HPO validation slice must NOT reuse the fold-assignment seed. With
# StratifiedGroupKFold(n_splits=5), a hold-out drawn at SPLIT_SEED reproduces
# fold 0 exactly, which would make that fold look optimistic later. A separate
# seed decorrelates the slice from every CV fold.
HPO_SLICE_SEED = 1337

TRAIN_SEED = 42          # base seed; fold k trains at TRAIN_SEED + k

# ------------------------------------------------------------- Fractions
TEST_FRAC = 0.20
HPO_FRAC  = 0.20
N_FOLDS   = 5

# Maximum sequence length, shared by every dataset in models.py. Generous for
# this corpus: the texts have a median of 8 and a mean of 9 whitespace tokens.
MAX_LEN = 128

# ---------------------------------------------- Fixed encoder hyperparameters
# The encoder side is fixed, not searched, and is identical for every
# architecture - a symmetric constraint, not a handicap for any one model.
#   batch_size   32    - canonical fine-tuning grid, Devlin et al. (2019, App. A.3).
#                        With ~7,880 training rows this gives ~247 steps/epoch.
#   weight_decay 0.01  - AdamW setting of the RoBERTa family, Liu et al. (2019);
#   warmup_ratio 0.10    XLM-R is a RoBERTa model, Conneau et al. (2020). The
#                        ratio is relative, so warmup scales with the searched
#                        epoch count instead of interacting with it.
#   encoder_lr   1e-5  - the established range for XLM-R-large is roughly
#                        5e-6 to 2e-5. Note this is NOT "below the BERT grid":
#                        that grid was tuned for a 110M/340M model, whereas
#                        XLM-R-large has 560M parameters and fine-tuning
#                        instability grows with model size (Mosbach et al.,
#                        2021), which also motivates the collapse guard below.
#                        A pilot under the earlier protocol selected 5e-6 for
#                        the dual-view model and 2e-5 for the baseline, so 1e-5
#                        is a deliberate midpoint held equal for both.
FIXED_ENCODER = {
    "batch_size":   32,
    "encoder_lr":   1e-5,
    "weight_decay": 0.01,
    "warmup_ratio": 0.10,
}

# ------------------------------------------------------ Head search space
# Searched exhaustively per architecture with an identical grid, so that no
# variant is tuned more thoroughly - or luckier - than another.
#
#   head_lr {1e-4, 5e-4, 1e-3, 2e-3}
#       A randomly initialised head needs a higher rate than the pretrained body
#       (discriminative fine-tuning, Howard and Ruder, 2018), so the grid spans
#       10x to 200x the encoder rate. The lower bound matters: the baseline's
#       classification head is a 1.05M-parameter MLP that standard fine-tuning
#       trains at the *encoder* rate, whereas the dual-view head is a 7.84M
#       from-scratch CNN-BiLSTM stack that wants far more. A grid starting at
#       5e-4 would have been chosen for the latter and imposed on the former,
#       excluding the baseline's plausible optimum from below - the mirror image
#       of the flaw this design fixes. It stops one order of magnitude above the
#       encoder rate because a head rate *equal* to it is exactly the
#       configuration the earlier protocol used and that this design corrects.
#
#   dropout {0.1, 0.3}
#       0.1 is the BERT default; 0.3 is already a wide excursion. 0.5 is excluded
#       on architectural grounds: the dual-view head applies dropout at three
#       points before the classifier, so a nominal 0.5 leaves an effective
#       retention near 0.125. Note the knob is not the same intervention in both
#       architectures - the baseline applies it once, in classifier_dropout -
#       which the paper states rather than glossing over.
#
#   epochs {3, 4, 5}
#       The canonical {2,3,4} of Devlin et al. (2019) shifted up by one: the
#       encoder learns at a deliberately gentle rate while the head converges
#       fast, so a little more exposure is reasonable. Gives 741/988/1,235
#       optimizer steps at batch 32.
HEAD_LR_GRID = [1e-4, 5e-4, 1e-3, 2e-3]
DROPOUT_GRID = [0.1, 0.3]
EPOCH_GRID   = [3, 4, 5]
EPOCH_MIN, EPOCH_MAX = min(EPOCH_GRID), max(EPOCH_GRID)

# The search is exhaustive (optuna GridSampler), not sampled: with only 24
# configurations a TPE sampler would add nothing but the risk that one
# architecture draws a lucky configuration and another does not. Because every
# point is visited, HPO_SEED no longer influences the outcome.
HPO_GRID = {
    "head_lr": HEAD_LR_GRID,
    "dropout": DROPOUT_GRID,
    "epochs":  EPOCH_GRID,
}
HPO_HEAD_TRIALS = len(HEAD_LR_GRID) * len(DROPOUT_GRID) * len(EPOCH_GRID)  # 24

# NOTE: the former baseline epoch robustness check (ROBUSTNESS_EPOCHS) has been
# removed. It only existed because the baseline inherited its epoch count from
# dual_view without a search of its own. Every architecture now searches its own
# head configuration - including the epoch count - so the search subsumes the
# check, and re-testing a value that was just selected on the same dev pool
# would not be independent evidence anyway.

# Collapse guard: if the mean training loss after epoch 1 exceeds ln(3) (the
# loss of a uniform 3-class predictor), the run has diverged - restart with a
# different seed instead of writing garbage into the OOF / test predictions.
import math
COLLAPSE_LOSS   = math.log(3)
COLLAPSE_RETRIES = 3

# ------------------------------------------------------------- Statistics
BOOTSTRAP_B    = 10000   # paired item-level bootstrap resamples
BOOTSTRAP_SEED = 2026
ASO_SEED       = 2026    # deep-significance Almost-Stochastic-Order test

# -------------------------------------------------------------- Variants
# dual_view_dupinput_v2 is the capacity-matched control: the dual-view model,
# unchanged, fed the surface view in place of the lemma view. Same parameters,
# same architecture, same configuration - the second view simply carries no
# additional information, and its cross-attention degenerates to self-attention.
# Comparing dual_view_v2 against it therefore isolates the *morphological
# information* rather than the capacity of the attention layer, which a
# single-view ablation cannot do: dropping the cross-attention would also drop
# 4.2M parameters and confound the two.
VARIANTS = [
    "baseline_v2",
    "dual_view_dupinput_v2",
    "dual_view_v2",
    "dual_view_gated_v2",
]

STUDY_NAMES = {
    "baseline_v2":           "baseline_v2_heldout",
    "dual_view_dupinput_v2": "dual_view_dupinput_v2_heldout",
    "dual_view_v2":          "dual_view_v2_heldout",
    "dual_view_gated_v2":    "dual_view_gated_v2_heldout",
}

# Which view feeds the second branch. dual_view_dupinput_v2 reads the surface
# column twice; every other dual-view variant reads the lemma column.
LEMMA_COL = {v: ("surface" if v == "dual_view_dupinput_v2" else "lemma")
             for v in VARIANTS}

# Which variants run their own head search, and which inherit one.
#   baseline_v2           - Roberta classification head, different -> own search
#   dual_view_v2          - cross-attention + CNN-BiLSTM head      -> own search
#   dual_view_dupinput_v2 - identical architecture, different input -> inherits
#   dual_view_gated_v2    - identical head plus a gate on head_lr   -> inherits
#
# The two inheriting variants *must* inherit rather than search. Both share
# dual_view's architecture exactly; giving them their own configuration would
# make the comparison against it two-variable again and destroy the very
# question they exist to answer. For dual_view_dupinput_v2 in particular, the
# whole point is that architecture and configuration are held constant while
# only the information in the second view changes.
#
# The two searching variants have genuinely different heads and therefore
# genuinely different optima, so each searches the same grid with the same
# exhaustive budget.
HPO_SEARCHES = ["baseline_v2", "dual_view_v2"]
HPO_INHERITS = {
    "dual_view_dupinput_v2": "dual_view_v2",
    "dual_view_gated_v2":    "dual_view_v2",
}


def _mk(p):
    os.makedirs(p, exist_ok=True)
    return p


def hpo_dir(variant):
    return _mk(f"{V2}/hpo/{variant}")


def cv_dir(variant):
    return _mk(f"{V2}/cv/{variant}")


def study_db(variant):
    return hpo_dir(variant) + "/study.db"


def final_model(variant):
    return f"{FINAL_MODELS}/{variant}_final.pth"


def fold_model(variant, fold):
    """Path of the CV fold model, fold is 1-based (matches the CV notebooks)."""
    return f"{cv_dir(variant)}/{variant}_fold{fold}.pth"


def best_params_path(variant):
    return hpo_dir(variant) + "/best_params.json"


def assert_test_untouched(namespace):
    ignore = {"TEST_LOCKED"}
    leaked = [k for k, v in namespace.items()
              if k not in ignore
              and not k.startswith("_")
              and isinstance(v, str) and "test_LOCKED" in v]
    assert not leaked, f"Test set referenced in: {leaked}"
    print("OK - test set not loaded in this notebook.")

