# Central configuration for the v2 Held-Out protocol.
#
# Usage in every v2 notebook:
#     import sys
#     sys.path.insert(0, "/content/drive/MyDrive/google_colab/kusa/v2_heldout")
#     from config import *
import os

# ---------------------------------------------------------------- Paths
# Portable: V2 is the directory that contains this config.py, so every data path
# below resolves relative to the checkout, in Colab or locally. Override with the
# KUSA_ROOT environment variable if config.py lives outside the project tree.
V2   = os.environ.get("KUSA_ROOT", os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.dirname(V2)

# All data resides within v2_heldout - the folder is self-contained.
DATA = V2 + "/datasets"

ORIGINAL     = DATA + "/KurdiSent.csv"                 # Raw corpus, read-only
PREPROCESSED = DATA + "/KurdiSent_preprocessed.csv"    # Generated by preprocess_kurdisent_v2

SPLITS      = V2 + "/splits"
DEV_POOL    = SPLITS + "/dev_pool.csv"
DEV_FOLDS   = SPLITS + "/dev_folds.csv"
TEST_LOCKED = SPLITS + "/test_LOCKED.csv"
MANIFEST    = SPLITS + "/split_manifest.json"
DISTRIB     = SPLITS + "/split_distribution.csv"

FINAL_MODELS = V2 + "/final_models"
TEST_EVAL    = V2 + "/test_eval"
ANALYSIS     = V2 + "/analysis"
ANNOTATION = V2 + "/annotation"

# ---------------------------------------------------------------- Seeds
SPLIT_SEED = 2026        # test hold-out AND fold assignment (build_split_v2)
HPO_SEED   = 2026        # Optuna TPE sampler seed only

# The HPO validation slice must NOT reuse the fold-assignment seed. With
# StratifiedGroupKFold(n_splits=5), a hold-out drawn at SPLIT_SEED reproduces
# fold 0 exactly, which would make that fold look optimistic later. A separate
# seed decorrelates the slice from every CV fold.
HPO_SLICE_SEED = 1337

TRAIN_SEED = 42          # base seed; fold k trains at TRAIN_SEED + k

# ------------------------------------------------------------- Fractions
TEST_FRAC = 0.20
HPO_FRAC  = 0.20
N_FOLDS   = 5

# ---------------------------------------------- Fixed encoder hyperparameters
# The encoder side is fixed, not searched, and is identical for every
# architecture. Sources for each value:
#   batch_size   32    - canonical fine-tuning grid, Devlin et al. (2019, App. A.3)
#   weight_decay 0.01  - AdamW setting of the RoBERTa family, Liu et al. (2019);
#   warmup_ratio 0.10    XLM-R is a RoBERTa model, Conneau et al. (2020)
#   encoder_lr   1e-5  - deliberately below the lowest BERT-grid value (2e-5):
#                        large-model fine-tuning destabilises at higher rates,
#                        Mosbach et al. (2021). Same source motivates the
#                        collapse guard below.
FIXED_ENCODER = {
    "batch_size":   32,
    "encoder_lr":   1e-5,
    "weight_decay": 0.01,
    "warmup_ratio": 0.10,
}

# Head search (head_lr, dropout, epochs), run per architecture with an equal
# budget so that no variant is tuned more thoroughly than another.
HPO_HEAD_TRIALS   = 10

# Epoch range, searched per architecture. Brackets the canonical {2,3,4} of
# Devlin et al. (2019), opened downwards because the earlier dual_view search
# selected the lower bound of its range. Search space and trial budget are
# identical for every architecture - that symmetry is what makes the comparison
# fair, not a shared configuration.
EPOCH_MIN, EPOCH_MAX = 3, 5

# Head search space, identical for every architecture:
#   head_lr {5e-4, 1e-3, 2e-3} - a randomly initialised head needs a higher rate
#                                than the pretrained body (Howard and Ruder, 2018)
#   dropout {0.1, 0.3, 0.5}    - standard regularisation range
#   epochs  {3, 4, 5}          - see above
HEAD_LR_GRID = [5e-4, 1e-3, 2e-3]
DROPOUT_GRID = [0.1, 0.3, 0.5]

# NOTE: the former baseline epoch robustness check (ROBUSTNESS_EPOCHS) has been
# removed. It only existed because the baseline inherited its epoch count from
# dual_view without a search of its own. Every architecture now searches its own
# head configuration - including the epoch count - so the search subsumes the
# check, and re-testing a value that was just selected on the same dev pool
# would not be independent evidence anyway.

# Collapse guard: if the mean training loss after epoch 1 exceeds ln(3) (the
# loss of a uniform 3-class predictor), the run has diverged - restart with a
# different seed instead of writing garbage into the OOF / test predictions.
import math
COLLAPSE_LOSS   = math.log(3)
COLLAPSE_RETRIES = 3

# ------------------------------------------------------------- Statistics
BOOTSTRAP_B    = 10000   # paired item-level bootstrap resamples
BOOTSTRAP_SEED = 2026
ASO_SEED       = 2026    # deep-significance Almost-Stochastic-Order test

# -------------------------------------------------------------- Variants
# single_view_complex_v2 is the ablation that separates the effect of the
# CNN-BiLSTM head from the effect of the second (lemma) view: it feeds the
# surface view alone through the same head, without cross-attention.
VARIANTS = [
    "baseline_v2",
    "single_view_complex_v2",
    "dual_view_v2",
    "dual_view_gated_v2",
]

STUDY_NAMES = {
    "baseline_v2":            "baseline_v2_heldout",
    "single_view_complex_v2": "single_view_complex_v2_heldout",
    "dual_view_v2":           "dual_view_v2_heldout",
    "dual_view_gated_v2":     "dual_view_gated_v2_heldout",
}

# Which variants run their own head search, and which inherit one.
#   baseline_v2            - Roberta classification head, different -> own search
#   dual_view_v2           - cross-attention + CNN-BiLSTM head      -> own search
#   single_view_complex_v2 - same head, single view                 -> own search
#   dual_view_gated_v2     - same head plus a gate governed by head_lr -> inherits
#
# The ablation searches even though its head matches dual_view's. It is the run
# that has to be able to REFUTE the claim that the second view matters, so it
# must compete in its best configuration: a model fed one view instead of two
# plausibly wants different regularisation. Inheriting would leave it open to the
# charge of being under-tuned exactly where a loss is the expected - and
# claim-supporting - outcome. Deciding to tune it only after seeing it lose would
# be worse still: that is an adaptive choice, a forking path even on dev data.
# The search is therefore pre-registered here, not made conditional.
#
# The gated variant still inherits: its gate introduces no additional
# hyperparameter, and it serves as a probe rather than as evidence.
HPO_SEARCHES = ["baseline_v2", "single_view_complex_v2", "dual_view_v2"]
HPO_INHERITS = {
    "dual_view_gated_v2": "dual_view_v2",
}


def _mk(p):
    os.makedirs(p, exist_ok=True)
    return p


def hpo_dir(variant):
    return _mk(f"{V2}/hpo/{variant}")


def cv_dir(variant):
    return _mk(f"{V2}/cv/{variant}")


def study_db(variant):
    return hpo_dir(variant) + "/study.db"


def final_model(variant):
    return f"{FINAL_MODELS}/{variant}_final.pth"


def fold_model(variant, fold):
    """Path of the CV fold model, fold is 1-based (matches the CV notebooks)."""
    return f"{cv_dir(variant)}/{variant}_fold{fold}.pth"


def best_params_path(variant):
    return hpo_dir(variant) + "/best_params.json"


def assert_test_untouched(namespace):
    ignore = {"TEST_LOCKED"}
    leaked = [k for k, v in namespace.items()
              if k not in ignore
              and not k.startswith("_")
              and isinstance(v, str) and "test_LOCKED" in v]
    assert not leaked, f"Test set referenced in: {leaked}"
    print("OK - test set not loaded in this notebook.")

