# Central configuration for the v2 Held-Out protocol.
#
# Usage in every v2 notebook:
#     import sys
#     sys.path.insert(0, "/content/drive/MyDrive/google_colab/kusa/v2_heldout")
#     from config import *
import os

# ---------------------------------------------------------------- Paths
# Portable: V2 is the directory that contains this config.py, so every data path
# below resolves relative to the checkout, in Colab or locally. Override with the
# KUSA_ROOT environment variable if config.py lives outside the project tree.
V2   = os.environ.get("KUSA_ROOT", os.path.dirname(os.path.abspath(__file__)))
ROOT = os.path.dirname(V2)

# All data resides within v2_heldout - the folder is self-contained.
DATA = V2 + "/datasets"

ORIGINAL     = DATA + "/KurdiSent.csv"                 # Raw corpus, read-only
PREPROCESSED = DATA + "/KurdiSent_preprocessed.csv"    # Generated by preprocess_kurdisent_v2

SPLITS      = V2 + "/splits"
DEV_POOL    = SPLITS + "/dev_pool.csv"
DEV_FOLDS   = SPLITS + "/dev_folds.csv"
TEST_LOCKED = SPLITS + "/test_LOCKED.csv"
MANIFEST    = SPLITS + "/split_manifest.json"
DISTRIB     = SPLITS + "/split_distribution.csv"

FINAL_MODELS = V2 + "/final_models"
TEST_EVAL    = V2 + "/test_eval"
ANALYSIS     = V2 + "/analysis"
ANNOTATION = V2 + "/annotation"

# ---------------------------------------------------------------- Seeds
SPLIT_SEED = 2026        # test hold-out AND fold assignment (build_split_v2)
HPO_SEED   = 2026        # Optuna TPE sampler seed only

# The HPO validation slice must NOT reuse the fold-assignment seed. With
# StratifiedGroupKFold(n_splits=5), a hold-out drawn at SPLIT_SEED reproduces
# fold 0 exactly, which would make that fold look optimistic later. A separate
# seed decorrelates the slice from every CV fold.
HPO_SLICE_SEED = 1337

TRAIN_SEED = 42          # base seed; fold k trains at TRAIN_SEED + k

# ------------------------------------------------------------- Fractions
TEST_FRAC = 0.20
HPO_FRAC  = 0.20
N_FOLDS   = 5

# ---------------------------------------------- Fixed encoder hyperparameters
# The encoder side is fixed, not searched. These are the established stable
# values for XLM-R-large; higher learning rates are exactly where fine-tuning
# runs collapse. Only the architecture-specific head is tuned, on the
# average-fusion variant, and transferred to the other two so that all three
# architectures share an identical training setup (isolating the fusion).
FIXED_ENCODER = {
    "batch_size":   32,
    "encoder_lr":   1e-5,
    "weight_decay": 0.01,
    "warmup_ratio": 0.10,
}

# Small head search (head_lr, dropout, epochs) on dual_view_v2 only.
HPO_HEAD_TRIALS   = 10
EPOCH_MIN, EPOCH_MAX = 4, 5

# Baseline epoch robustness check (Option 3): confirm that the epoch count
# transferred from dual_view does not disadvantage the baseline. These counts
# are compared on the dev CV only - the test set is never touched.
ROBUSTNESS_EPOCHS = [4, 5]

# Collapse guard: if the mean training loss after epoch 1 exceeds ln(3) (the
# loss of a uniform 3-class predictor), the run has diverged - restart with a
# different seed instead of writing garbage into the OOF / test predictions.
import math
COLLAPSE_LOSS   = math.log(3)
COLLAPSE_RETRIES = 3

# ------------------------------------------------------------- Statistics
BOOTSTRAP_B    = 10000   # paired item-level bootstrap resamples
BOOTSTRAP_SEED = 2026
ASO_SEED       = 2026    # deep-significance Almost-Stochastic-Order test

# -------------------------------------------------------------- Variants
VARIANTS = ["baseline_v2", "dual_view_v2", "dual_view_gated_v2"]

STUDY_NAMES = {
    "baseline_v2":        "baseline_v2_heldout",
    "dual_view_v2":       "dual_view_v2_heldout",
    "dual_view_gated_v2": "dual_view_gated_v2_heldout",
}


def _mk(p):
    os.makedirs(p, exist_ok=True)
    return p


def hpo_dir(variant):
    return _mk(f"{V2}/hpo/{variant}")


def cv_dir(variant):
    return _mk(f"{V2}/cv/{variant}")


def study_db(variant):
    return hpo_dir(variant) + "/study.db"


def final_model(variant):
    return f"{FINAL_MODELS}/{variant}_final.pth"


def fold_model(variant, fold):
    """Path of the CV fold model, fold is 1-based (matches the CV notebooks)."""
    return f"{cv_dir(variant)}/{variant}_fold{fold}.pth"


def best_params_path(variant):
    return hpo_dir(variant) + "/best_params.json"


def assert_test_untouched(namespace):
    ignore = {"TEST_LOCKED"}
    leaked = [k for k, v in namespace.items()
              if k not in ignore
              and not k.startswith("_")
              and isinstance(v, str) and "test_LOCKED" in v]
    assert not leaked, f"Test set referenced in: {leaked}"
    print("OK - test set not loaded in this notebook.")

